//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point EditorMainPos {
            get {
                return ((global::System.Drawing.Point)(this["EditorMainPos"]));
            }
            set {
                this["EditorMainPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FileRegPos {
            get {
                return ((global::System.Drawing.Point)(this["FileRegPos"]));
            }
            set {
                this["FileRegPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size EditorMainSize {
            get {
                return ((global::System.Drawing.Size)(this["EditorMainSize"]));
            }
            set {
                this["EditorMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 300")]
        public global::System.Drawing.Size FileRegSize {
            get {
                return ((global::System.Drawing.Size)(this["FileRegSize"]));
            }
            set {
                this["FileRegSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EntityViewPos {
            get {
                return ((global::System.Drawing.Point)(this["EntityViewPos"]));
            }
            set {
                this["EntityViewPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 300")]
        public global::System.Drawing.Size EntityViewSize {
            get {
                return ((global::System.Drawing.Size)(this["EntityViewSize"]));
            }
            set {
                this["EntityViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FileRegVisible {
            get {
                return ((bool)(this["FileRegVisible"]));
            }
            set {
                this["FileRegVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EntityViewVisible {
            get {
                return ((bool)(this["EntityViewVisible"]));
            }
            set {
                this["EntityViewVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 0")]
        public global::System.Drawing.Point SceneViewPos {
            get {
                return ((global::System.Drawing.Point)(this["SceneViewPos"]));
            }
            set {
                this["SceneViewPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 300")]
        public global::System.Drawing.Size SceneViewSize {
            get {
                return ((global::System.Drawing.Size)(this["SceneViewSize"]));
            }
            set {
                this["SceneViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SceneViewVisible {
            get {
                return ((bool)(this["SceneViewVisible"]));
            }
            set {
                this["SceneViewVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int SceneViewSplitDistance {
            get {
                return ((int)(this["SceneViewSplitDistance"]));
            }
            set {
                this["SceneViewSplitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int EntityFlowContWidth {
            get {
                return ((int)(this["EntityFlowContWidth"]));
            }
            set {
                this["EntityFlowContWidth"] = value;
            }
        }
    }
}
